### ISSUE TITLE
Calling dataset methods from child class in STI causes NoMethodError

### ISSUE THREAD

**Issue by hromadkom** [jeremyevans/sequel#1284]
### Complete Description of Issue
Hi,
update to version 4.42.0 caused me a problem with dataset methods defined in parent class of model using Single Table Inheritance. When I want to call dataset method from child class I get NoMethodError. In example `Photo.dataset.verified` call causes the problem.

### Simplest Possible Self-Contained Example Showing the Bug
```
DB = Sequel.connect('sqlite://database.db')

DB.create_table(:files) do
  primary_key :id

  column :status, 'smallint', null: false
  column :type, 'smallint', null: false
  column :created_at, 'timestamp without time zone', null: false
  column :updated_at, 'timestamp without time zone', null: false
end

class DbFile < Sequel::Model(:files)

  plugin :single_table_inheritance, :type, model_map: { 1 => :Photo }
  plugin :timestamps, create: :created_at,
                      update: :updated_at, update_on_create: true

  dataset_module do
    def verified
      where(files__status: 3)
    end
  end
end

class Photo < DbFile
end

Photo.create(
  status: 3
)

Photo.dataset.verified
```
### Full Backtrace of Exception (if any)
```
undefined method `verified' for #<#<Class:0x007ff5fd3363f0>:0x007ff5fd2ff148> (NoMethodError)
```

**Comment by jeremyevans** [comment]
Thanks for the report. This certainly looks like a bug to me.  I'll look into it later today.  Since this appears to be a regression from a previous version, I'll probably release 4.42.1 with a fix.

**Comment by jeremyevans** [comment]
OK, the bug fix was fairly simple, as I expected.  As this appears to be a regression between 4.41.0 and 4.42.0, I'll work on a 4.42.1 release, it should be available later today.

**Comment by hromadkom** [comment]
Perfect! Thanks
