### ISSUE TITLE
undefined method `join' for Sequel::SQL::AliasedExpression 

### ISSUE THREAD

**Issue by bbozo** [jeremyevans/sequel#1474]
### Complete Description of Issue

I'm trying to do a self-joining query, it'll be a triple self-join so I really really want to alias every part of the query, I tried something that seemingly worked on an older version of Sequel (4.45), but this no longer works I guess:

``` ruby
DB[:market_pairs___mp_a].join(Sequel[:market_pairs___mp_b])
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"market_pairs___mp_a\" INNER JOIN \"market_pairs___mp_b\"">
```

I found resources online that `#as` should be used for aliasing and it works for the join part:

``` ruby
 DB[:market_pairs].join(Sequel[:market_pairs].as(:mp_b))
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"market_pairs\" INNER JOIN \"market_pairs\" AS \"mp_b\"">
```

but not in the 1st query part:

``` ruby
puts DB[:market_pairs].as(:mp_a).join(Sequel[:market_pairs].as(:mp_b)).sql
NoMethodError: undefined method `join' for #<Sequel::SQL::AliasedExpression:0x00000003afae30>
```

### Full Backtrace of Exception (if any)

The Sequel part of the backtrace is:

``` ruby
/home/bbozo/.rvm/gems/ruby-2.3.4/gems/sequel-5.4.0/lib/sequel/database/transactions.rb:197:in `_transaction'
/home/bbozo/.rvm/gems/ruby-2.3.4/gems/sequel-5.4.0/lib/sequel/database/transactions.rb:179:in `block in transaction'
/home/bbozo/.rvm/gems/ruby-2.3.4/gems/sequel-5.4.0/lib/sequel/database/connecting.rb:264:in `block in synchronize'
/home/bbozo/.rvm/gems/ruby-2.3.4/gems/sequel-5.4.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
/home/bbozo/.rvm/gems/ruby-2.3.4/gems/sequel-5.4.0/lib/sequel/database/connecting.rb:264:in `synchronize'
/home/bbozo/.rvm/gems/ruby-2.3.4/gems/sequel-5.4.0/lib/sequel/database/transactions.rb:145:in `transaction'
```

I'm running sequel (5.4.0) on ruby 2.3.4p301

**Comment by jeremyevans** [comment]
Support for splitting symbols (the double/triple underscore stuff) was deprecated in Sequel 4.46.0 and removed in Sequel 5.0, and mentioned in the release notes for both versions.  So that breakage is expected.  You can enable the historical behavior by doing `Sequel.split_symbols = true`.

You can change to:

```ruby
 DB[Sequel[:market_pairs].as(:mp_a)].join(Sequel[:market_pairs].as(:mp_b))
```
