### ISSUE TITLE
Sequel doesn't work with ruby-mysql 3.0.0.

### ISSUE THREAD

**Issue by shakiyam** [jeremyevans/sequel#1795]
### Complete Description of Issue

Sequel doesn't work with ruby-mysql 3.0.0.

### Simplest Possible Self-Contained Example Showing the Bug

```
# gem list --local | grep -E '(ruby-mysql|sequel)'
ruby-mysql (3.0.0)
sequel (5.51.0)
# irb
irb(main):001:0> require 'sequel'
=> true
irb(main):002:0> DB = Sequel.connect("mysql://user:pass@host:3306/database")
/usr/local/bundle/gems/sequel-5.51.0/lib/sequel/adapters/mysql.rb:74:in `connect': NoMethodError: undefined method `init' for Mysql:Class (Sequel::DatabaseConnectionError)
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/connection_pool.rb:122:in `make_new'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/database/connecting.rb:269:in `synchronize'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/database/connecting.rb:278:in `test_connection'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/database/misc.rb:175:in `initialize'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/database/connecting.rb:57:in `new'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/database/connecting.rb:57:in `connect'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/core.rb:124:in `connect'
        from (irb):2:in `<main>'
        from /usr/local/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
        from /usr/local/bin/irb:23:in `load'
        from /usr/local/bin/irb:23:in `<main>'
/usr/local/bundle/gems/sequel-5.51.0/lib/sequel/adapters/mysql.rb:74:in `connect': undefined method `init' for Mysql:Class (NoMethodError)
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/connection_pool.rb:122:in `make_new'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/database/connecting.rb:269:in `synchronize'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/database/connecting.rb:278:in `test_connection'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/database/misc.rb:175:in `initialize'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/database/connecting.rb:57:in `new'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/database/connecting.rb:57:in `connect'
        from /usr/local/bundle/gems/sequel-5.51.0/lib/sequel/core.rb:124:in `connect'
        from (irb):2:in `<main>'
        from /usr/local/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
        from /usr/local/bin/irb:23:in `load'
        from /usr/local/bin/irb:23:in `<main>'
```

ruby-mysql 2.11.1 works as expected.

```
# gem list --local | grep -E '(ruby-mysql|sequel)'
ruby-mysql (2.11.1)
sequel (5.51.0)
# irb
irb(main):001:0> require 'sequel'
=> true
irb(main):002:0> DB = Sequel.connect("mysql://user:pass@host:3306/database")
=> #<Sequel::MySQL::Database: "mysql://user:pass@host:3306/database">
```

**Comment by jeremyevans** [comment]
Sequel's mysql adapter was designed to work with the mysql gem, not the ruby-mysql gem.  If it worked with older versions of ruby-mysql, it was purely a coincidence and not by design.  I wasn't aware it even worked with the pure ruby driver.  The last time I tested the pure ruby driver, it didn't work, but that was many years ago.  The documentation is very clear about this: `The MySQL adapter does not support the pure-ruby mysql.rb driver, it requires the C-extension driver.` So this definitely isn't a bug.

That being said, if ruby-mysql 2.11.1 gem works with Sequel's mysql adapter and passes the mysql adapter tests, I can see about adding it to my test matrix, and modifying the mysql adapter to support ruby-mysql 3.0.0.  However, if the ruby-mysql 2.11.1 driver does not pass the mysql adapter tests, then I will not make changes to support ruby-mysql 3.0.0.

**Comment by jeremyevans** [comment]
I tested this an other than a minor issue, the tests do pass with ruby-mysql 2.11.1.  So I'm going to reopen this and add support for ruby-mysql 3.0.0.

**Comment by astounding** [comment]
Thanks for your work making 3.0.0 work!  Much appreciated!!!
