### ISSUE TITLE
sequel (4.30.0) on JRuby 9.0.5.0 NoMethodError - undefined method `field' for #<Java::OrgPostgresqlJdbc4::Jdbc4ResultSetMetaData:0x5b81b835>

### ISSUE THREAD

**Issue by PetrKaleta** [jeremyevans/sequel#1137]
I've just upgraded to `JRuby 9.0.5.0` using `sequel (4.30.0)` and `jdbc-postgres (9.4.1204)`.

When I call `SomeModel.all` it fails on:

```
NoMethodError: undefined method `field' for #<Java::OrgPostgresqlJdbc4::Jdbc4ResultSetMetaData:0x66908415>
from /Users/Petr/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/sequel-4.30.0/lib/sequel/adapters/jdbc/postgresql.rb:196:in `type_convertor'
```

**Comment by jeremyevans** [comment]
Can you try dropping back to jdbc-postgres 9.4.1200?  I've noticed bugs with 9.4.1204, though not that one specifically.

**Comment by jeremyevans** [comment]
Actually, I've just tested JRuby 9.0.5.0, and I get the same issue.  I'm guessing now it is a bug in JRuby.  I'll do some more testing.

**Comment by jeremyevans** [comment]
This is a JRuby regression between 9.0.4.0 and 9.0.5.0.  It's no longer calling the Java `getField` function when the ruby `field` method is called. I've filed a JRuby bug for this: https://github.com/jruby/jruby/issues/3622

 I'll commit a workaround shortly allowing Sequel to work with JRuby 9.0.5.0.
