### ISSUE TITLE
Old test fails when moving from 4.31.0 to 4.32.0

### ISSUE THREAD

**Issue by auxbuss** [jeremyevans/sequel#1166]
I have a test for a cascade delete:
```
class DiscovererDeleteTest < SequelTestCase

  def test_discoverer_delete
    create :timezone
    user      = create :user, uname: 'discoverer'
    encounter = create :encounter, uname: 'encounter'

    # checkins

    assert_equal false, user.checked_in_to?(encounter)
    assert_kind_of Checkin, user.check_in_to(encounter)
    assert_equal 1, Checkin.count

    # collections

    assert_nil user.collection
    user.collection(create :collection, user_id: user.id)
    assert_equal 1, Collection.count
    assert_kind_of Collection, user.refresh.collection
...
```
This has worked fine for years. When updating to sequel 4.32.0 from 4.31.0, the following line fails:
```
    user.collection(create :collection, user_id: user.id)
```
with
```
  1) Error:
DiscovererDeleteTest#test_discoverer_delete:
NoMethodError: undefined method `[]' for nil:NilClass
    /Users/marc/.rvm/gems/ruby-2.2.1@fndout/gems/sequel-4.32.0/lib/sequel/model/associations.rb:2289:in `load_associated_objects'
    /Users/marc/.rvm/gems/ruby-2.2.1@fndout/gems/sequel-4.32.0/lib/sequel/model/associations.rb:1771:in `block in def_association_method'
    test/models/delete_discoverer_test.rb:19:in `test_discoverer_delete'
```
The association in `User` looks like this:
```
class User < Sequel::Model(:users)
...
  one_to_one   :collection
...
```
and for `Collection`
```
class Collection < Sequel::Model(:collections)

  one_to_one :user
...
```
I've looked through the changelog and can see that changes have taken place around associations, but I can't see what is causing this new problem.

**Comment by jeremyevans** [comment]
I think I see the problem.  You must be passing a value that isn't a hash, true, false, nil, or an object that responds to call as the second argument to the association method.  It's arguable whether that should be an error.  For greatest backwards compatibility, I think I should just use `{:reload=>true}` in that case, as the historical API before an options hash was supported was that any truthy object means reload.  I'll commit a fix for this shortly.
